// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_smart_contract_counter/test/dart/counter/state_managers/counter_cubit/counter_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter_smart_contract_counter/core/error/failure.dart' as _i6;
import 'package:flutter_smart_contract_counter/core/use_case.dart' as _i7;
import 'package:flutter_smart_contract_counter/counter/repositories/counter_repository.dart'
    as _i2;
import 'package:flutter_smart_contract_counter/counter/use_cases/get_counter.dart'
    as _i4;
import 'package:flutter_smart_contract_counter/counter/use_cases/increment_counter.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCounterRepository_0 extends _i1.Fake
    implements _i2.CounterRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetCounter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCounter extends _i1.Mock implements _i4.GetCounter {
  MockGetCounter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CounterRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeCounterRepository_0()) as _i2.CounterRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, int>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, int>>.value(
                  _FakeEither_1<_i6.Failure, int>()))
          as _i5.Future<_i3.Either<_i6.Failure, int>>);
}

/// A class which mocks [IncrementCounter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementCounter extends _i1.Mock implements _i8.IncrementCounter {
  MockIncrementCounter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CounterRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeCounterRepository_0()) as _i2.CounterRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
                  _FakeEither_1<_i6.Failure, _i3.Unit>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}
