// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_nft_minting/test/dart/nft/state_managers/nft_cubit/nft_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter_nft_minting/core/error/failure.dart' as _i6;
import 'package:flutter_nft_minting/core/use_case.dart' as _i7;
import 'package:flutter_nft_minting/nft/repositories/nft_repository.dart'
    as _i2;
import 'package:flutter_nft_minting/nft/use_cases/get_name.dart' as _i4;
import 'package:flutter_nft_minting/nft/use_cases/get_symbol.dart' as _i8;
import 'package:flutter_nft_minting/nft/use_cases/get_token_counter.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeNFTRepository_0 extends _i1.Fake implements _i2.NFTRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetName].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetName extends _i1.Mock implements _i4.GetName {
  MockGetName() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NFTRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeNFTRepository_0()) as _i2.NFTRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [GetSymbol].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSymbol extends _i1.Mock implements _i8.GetSymbol {
  MockGetSymbol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NFTRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeNFTRepository_0()) as _i2.NFTRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [GetTokenCounter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTokenCounter extends _i1.Mock implements _i9.GetTokenCounter {
  MockGetTokenCounter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NFTRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeNFTRepository_0()) as _i2.NFTRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, int>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, int>>.value(
                  _FakeEither_1<_i6.Failure, int>()))
          as _i5.Future<_i3.Either<_i6.Failure, int>>);
}
